# Generated by Django 3.0.7 on 2020-07-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairstats',
            name='refdate',
            field=models.DateField(),
        ),
    ]
