# Generated by Django 3.2.18 on 2023-12-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0003_auto_20231130_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairstats',
            name='success',
        ),
    ]
