# Generated by Django 2.0 on 2019-08-11 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_quotes_htimestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairstats',
            name='beta_rotation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
