# Generated by Django 2.0 on 2019-09-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190811_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
