# Generated by Django 3.2.18 on 2023-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20201208_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CointParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adf_pvalue', models.FloatField(blank=True, null=True)),
                ('resid_std', models.FloatField(blank=True, null=True)),
                ('zscore', models.FloatField(blank=True, null=True)),
                ('ang_coef', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('last_resid', models.FloatField(blank=True, null=True)),
                ('half_life', models.FloatField(blank=True, null=True)),
                ('hurst', models.FloatField(blank=True, null=True)),
                ('n_observ', models.IntegerField(blank=True, null=True)),
                ('timestamp_calc', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pairstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pairstats',
            name='model_params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
