# Generated by Django 2.0 on 2019-09-24 02:07

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 Ações'), ('COINBASE', 'Coinbase (Crypo)')], default='N/A', max_length=2)),
                ('model_params', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('beta_rotation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('ativo_x', models.CharField(max_length=32)),
                ('ativo_y', models.CharField(max_length=32)),
                ('qnt_x', models.IntegerField()),
                ('qnt_y', models.IntegerField()),
                ('entry_x', models.FloatField()),
                ('entry_y', models.FloatField()),
                ('exit_x', models.FloatField(blank=True, null=True)),
                ('exit_y', models.FloatField(blank=True, null=True)),
                ('t_entry', models.DateField(auto_now_add=True)),
                ('t_exit', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
