# Generated by Django 2.0 on 2019-07-25 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adf_pvalue', models.FloatField(blank=True, null=True)),
                ('resid_std', models.FloatField(blank=True, null=True)),
                ('ang_coef', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('last_resid', models.FloatField(blank=True, null=True)),
                ('timestamp_calc', models.DateTimeField(auto_now_add=True)),
                ('pair', models.CharField(max_length=32, unique=True)),
                ('success', models.BooleanField(default=False)),
                ('market', models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 Ações'), ('COINBASE', 'Coinbase (Crypo)')], default='N/A', max_length=32)),
                ('ticker_x', models.CharField(max_length=32)),
                ('ticker_y', models.CharField(max_length=32)),
                ('x_quote', models.FloatField(blank=True, null=True)),
                ('y_quote', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adf_pvalue', models.FloatField(blank=True, null=True)),
                ('resid_std', models.FloatField(blank=True, null=True)),
                ('ang_coef', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('last_resid', models.FloatField(blank=True, null=True)),
                ('timestamp_calc', models.DateTimeField(auto_now_add=True)),
                ('ativo_x', models.CharField(max_length=32)),
                ('ativo_y', models.CharField(max_length=32)),
                ('market', models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 Ações'), ('COINBASE', 'Coinbase (Crypo)')], default='N/A', max_length=2)),
                ('qnt_x', models.IntegerField()),
                ('qnt_y', models.IntegerField()),
                ('entry_x', models.FloatField()),
                ('entry_y', models.FloatField()),
                ('exit_x', models.FloatField(blank=True, null=True)),
                ('exit_y', models.FloatField(blank=True, null=True)),
                ('t_entry', models.DateField(auto_now_add=True)),
                ('t_exit', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
