# Generated by Django 2.0 on 2019-07-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairstats',
            name='zscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='zscore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
