# Generated by Django 2.0 on 2019-07-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190727_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairstats',
            name='n_observ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='n_observ',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
