# Generated by Django 2.0 on 2019-08-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190728_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairstats',
            name='pair',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='pairstats',
            unique_together={('pair', 'n_observ')},
        ),
    ]
