# Generated by Django 2.0 on 2019-08-10 23:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='htimestamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, size=None),
            preserve_default=False,
        ),
    ]
