# Generated by Django 3.0.7 on 2020-06-15 16:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190924_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairstats',
            name='model_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
