# Generated by Django 3.0.7 on 2020-12-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200615_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairstats',
            name='market',
            field=models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 (Ações Brasileiras)'), ('BINANCE', 'Binance Futures (Crypto)')], default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='market',
            field=models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 (Ações Brasileiras)'), ('BINANCE', 'Binance Futures (Crypto)')], default='N/A', max_length=32),
        ),
    ]
