# Generated by Django 3.0.7 on 2020-06-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertrading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 Ações'), ('COINBASE', 'Coinbase (Crypo)')], default='N/A', max_length=8),
        ),
    ]
