# Generated by Django 3.2.18 on 2023-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papertrading', '0003_auto_20200615_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 (Ações Brasileiras)'), ('BINANCE', 'Binance Futures (Crypto)')], default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='trade',
            name='model_params',
            field=models.JSONField(default=dict),
        ),
    ]
