# Generated by Django 3.0.7 on 2020-07-08 15:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PairStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('N/A', 'N/A'), ('BOVESPA', 'B3 (Ações Brasileiras)'), ('BINANCE', 'Binance Futures (Crypto)')], default='N/A', max_length=32)),
                ('ticker_x', models.CharField(max_length=32)),
                ('ticker_y', models.CharField(max_length=32)),
                ('x_quote', models.FloatField(blank=True, null=True)),
                ('y_quote', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('model_params', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('beta_rotation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pair', models.CharField(max_length=32)),
                ('refdate', models.DateTimeField()),
            ],
            options={
                'unique_together': {('pair', 'refdate')},
            },
        ),
    ]
