# Generated by Django 3.2.18 on 2023-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_auto_20200709_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pairstats',
            name='model_params',
            field=models.JSONField(default=dict),
        ),
    ]
